import tensorflow as tf
import tensorflow_hub as hub
import matplotlib.pyplot as plt
import numpy as np
import os
import pandas as pd
#import re
import psutil
import humanize
import argparse
import sys
import pickle
from google.cloud import language
from google.cloud.language import enums
from google.cloud.language import types
import six

def rmse(predictions, targets):
    return np.sqrt(((predictions - targets)**2).mean())

if len(sys.argv) > 1:
    lines = sys.argv[1]
else:
    lines =  "What's the weather forecast for this afternoon?"
# lines = sys.argv[1]

# messages2 =[
# "What's the WASHINGTON for this afternoon?",
# "What's the SCHOOL for this afternoon?",
# "What's the MEETING for this afternoon?",
# "What's the MONALISA for this afternoon?",
# "What's the NOTEBOOK for this afternoon?",
# "What's the SOMETHING for this afternoon?",
#
# "What's the WASHINGTON like on my WASHINGTON?",
# "What's the WASHINGTON like on my SOMETHING?",
# "What's the SOMETHING like on my WASHINGTON?",
# "What's the SOMETHING like on my SOMETHING?",
#
# "Show me a WASHINGTON on WASHINGTON and WASHINGTON.",
# "Show me a WASHINGTON on WASHINGTON and SOMETHING.",
# "Show me a WASHINGTON on WASHINGTON and SCHOOL.",
# "Show me a WASHINGTON on SOMETHING and WASHINGTON.",
# "Show me a WASHINGTON on SOMETHING and SCHOOL.",
# "Show me a WASHINGTON on SOMETHING and SOMETHING.",
# "Show me a WASHINGTON on SCHOOL and WASHINGTON.",
# "Show me a WASHINGTON on SCHOOL and SOMETHING.",
# "Show me a WASHINGTON on SCHOOL and SCHOOL.",
#
# "Show me a SOMETHING on WASHINGTON and WASHINGTON.",
# "Show me a SOMETHING on WASHINGTON and SOMETHING.",
# "Show me a SOMETHING on WASHINGTON and SCHOOL.",
# "Show me a SOMETHING on SOMETHING and WASHINGTON.",
# "Show me a SOMETHING on SOMETHING and SCHOOL.",
# "Show me a SOMETHING on SOMETHING and SOMETHING.",
# "Show me a SOMETHING on SCHOOL and WASHINGTON.",
# "Show me a SOMETHING on SCHOOL and SOMETHING.",
# "Show me a SOMETHING on SCHOOL and SCHOOL.",
#
# "Show me a SCHOOL on WASHINGTON and WASHINGTON.",
# "Show me a SCHOOL on WASHINGTON and SOMETHING.",
# "Show me a SCHOOL on WASHINGTON and SCHOOL.",
# "Show me a SCHOOL on SOMETHING and WASHINGTON.",
# "Show me a SCHOOL on SOMETHING and SCHOOL.",
# "Show me a SCHOOL on SOMETHING and SOMETHING.",
# "Show me a SCHOOL on SCHOOL and WASHINGTON.",
# "Show me a SCHOOL on SCHOOL and SOMETHING.",
# "Show me a SCHOOL on SCHOOL and SCHOOL.",
#
# "Can you find me a WASHINGTON with WASHINGTON nearby?",
# "Can you find me a WASHINGTON with SOMETHING nearby?",
# "Can you find me a WASHINGTON with SCHOOL nearby?",
# "Can you find me a SOMETHING with WASHINGTON nearby?",
# "Can you find me a SOMETHING with SOMETHING nearby?",
# "Can you find me a SOMETHING with SCHOOL nearby?",
# "Can you find me a SCHOOL with WASHINGTON nearby?",
# "Can you find me a SCHOOL with SOMETHING nearby?",
# "Can you find me a SCHOOL with SCHOOL nearby?",
#
# "Find a WASHINGTON along WASHINGTON.",
# "Find a WASHINGTON along SOMETHING.",
# "Find a WASHINGTON along SCHOOL.",
# "Find a SOMETHING along WASHINGTON.",
# "Find a SOMETHING along SOMETHING.",
# "Find a SOMETHING along SCHOOL.",
# "Find a SCHOOL along WASHINGTON.",
# "Find a SCHOOL along SOMETHING.",
# "Find a SCHOOL along SCHOOL.",
#
# "Find the cheapest indoor WASHINGTON within 500 meters of my WASHINGTON.",
# "Find the cheapest indoor WASHINGTON within 500 meters of my SOMETHING.",
# "Find the cheapest indoor WASHINGTON within 500 meters of my SCHOOL.",
# "Find the cheapest indoor SOMETHING within 500 meters of my WASHINGTON.",
# "Find the cheapest indoor SOMETHING within 500 meters of my SOMETHING.",
# "Find the cheapest indoor SOMETHING within 500 meters of my SCHOOL.",
# "Find the cheapest indoor SCHOOL within 500 meters of my WASHINGTON.",
# "Find the cheapest indoor SCHOOL within 500 meters of my SOMETHING.",
# "Find the cheapest indoor SCHOOL within 500 meters of my SCHOOL.",
#
# "Okay, can you find me a WASHINGTON on my WASHINGTON that has a WASHINGTON?",
# "Okay, can you find me a WASHINGTON on my WASHINGTON that has a SOMETHING?",
# "Okay, can you find me a WASHINGTON on my WASHINGTON that has a SCHOOL?",
# "Okay, can you find me a WASHINGTON on my SOMETHING that has a WASHINGTON?",
# "Okay, can you find me a WASHINGTON on my SOMETHING that has a SOMETHING?",
# "Okay, can you find me a WASHINGTON on my SOMETHING that has a SCHOOL?",
# "Okay, can you find me a WASHINGTON on my SCHOOL that has a WASHINGTON?",
# "Okay, can you find me a WASHINGTON on my SCHOOL that has a SOMETHING?",
# "Okay, can you find me a WASHINGTON on my SCHOOL that has a SCHOOL?",
#
# "Okay, can you find me a SOMETHING on my WASHINGTON that has a WASHINGTON?",
# "Okay, can you find me a SOMETHING on my WASHINGTON that has a SOMETHING?",
# "Okay, can you find me a SOMETHING on my WASHINGTON that has a SCHOOL?",
# "Okay, can you find me a SOMETHING on my SOMETHING that has a WASHINGTON?",
# "Okay, can you find me a SOMETHING on my SOMETHING that has a SOMETHING?",
# "Okay, can you find me a SOMETHING on my SOMETHING that has a SCHOOL?",
# "Okay, can you find me a SOMETHING on my SCHOOL that has a WASHINGTON?",
# "Okay, can you find me a SOMETHING on my SCHOOL that has a SOMETHING?",
# "Okay, can you find me a SOMETHING on my SCHOOL that has a SCHOOL?",
#
# "Okay, can you find me a SCHOOL on my WASHINGTON that has a WASHINGTON?",
# "Okay, can you find me a SCHOOL on my WASHINGTON that has a SOMETHING?",
# "Okay, can you find me a SCHOOL on my WASHINGTON that has a SCHOOL?",
# "Okay, can you find me a SCHOOL on my SOMETHING that has a WASHINGTON?",
# "Okay, can you find me a SCHOOL on my SOMETHING that has a SOMETHING?",
# "Okay, can you find me a SCHOOL on my SOMETHING that has a SCHOOL?",
# "Okay, can you find me a SCHOOL on my SCHOOL that has a WASHINGTON?",
# "Okay, can you find me a SCHOOL on my SCHOOL that has a SOMETHING?",
# "Okay, can you find me a SCHOOL on my SCHOOL that has a SCHOOL?",
#
# "Find WASHINGTON near destination that accepts WASHINGTON and has a WASHINGTON.",
# "Find WASHINGTON near destination that accepts WASHINGTON and has a SOMETHING.",
# "Find WASHINGTON near destination that accepts WASHINGTON and has a SCHOOL.",
# "Find WASHINGTON near destination that accepts SOMETHING and has a WASHINGTON.",
# "Find WASHINGTON near destination that accepts SOMETHING and has a SOMETHING.",
# "Find WASHINGTON near destination that accepts SOMETHING and has a SCHOOL.",
# "Find WASHINGTON near destination that accepts SCHOOL and has a WASHINGTON.",
# "Find WASHINGTON near destination that accepts SCHOOL and has a SOMETHING.",
# "Find WASHINGTON near destination that accepts SCHOOL and has a SCHOOL.",
#
# "Find SOMETHING near destination that accepts WASHINGTON and has a WASHINGTON.",
# "Find SOMETHING near destination that accepts WASHINGTON and has a SOMETHING.",
# "Find SOMETHING near destination that accepts WASHINGTON and has a SCHOOL.",
# "Find SOMETHING near destination that accepts SOMETHING and has a WASHINGTON.",
# "Find SOMETHING near destination that accepts SOMETHING and has a SOMETHING.",
# "Find SOMETHING near destination that accepts SOMETHING and has a SCHOOL.",
# "Find SOMETHING near destination that accepts SCHOOL and has a WASHINGTON.",
# "Find SOMETHING near destination that accepts SCHOOL and has a SOMETHING.",
# "Find SOMETHING near destination that accepts SCHOOL and has a SCHOOL.",
#
# "Find SCHOOL near destination that accepts WASHINGTON and has a WASHINGTON.",
# "Find SCHOOL near destination that accepts WASHINGTON and has a SOMETHING.",
# "Find SCHOOL near destination that accepts WASHINGTON and has a SCHOOL.",
# "Find SCHOOL near destination that accepts SOMETHING and has a WASHINGTON.",
# "Find SCHOOL near destination that accepts SOMETHING and has a SOMETHING.",
# "Find SCHOOL near destination that accepts SOMETHING and has a SCHOOL.",
# "Find SCHOOL near destination that accepts SCHOOL and has a WASHINGTON.",
# "Find SCHOOL near destination that accepts SCHOOL and has a SOMETHING.",
# "Find SCHOOL near destination that accepts SCHOOL and has a SCHOOL.",
#
# "Find MONALISA near destination that accepts WASHINGTON and has a WASHINGTON.",
# "Find MONALISA near destination that accepts WASHINGTON and has a SOMETHING.",
# "Find MONALISA near destination that accepts WASHINGTON and has a SCHOOL.",
# "Find MONALISA near destination that accepts SOMETHING and has a WASHINGTON.",
# "Find MONALISA near destination that accepts SOMETHING and has a SOMETHING.",
# "Find MONALISA near destination that accepts SOMETHING and has a SCHOOL.",
# "Find MONALISA near destination that accepts SCHOOL and has a WASHINGTON.",
# "Find MONALISA near destination that accepts SCHOOL and has a SOMETHING.",
# "Find MONALISA near destination that accepts SCHOOL and has a SCHOOL.",
#
# "Find NOTEBOOK near destination that accepts WASHINGTON and has a WASHINGTON.",
# "Find NOTEBOOK near destination that accepts WASHINGTON and has a SOMETHING.",
# "Find NOTEBOOK near destination that accepts WASHINGTON and has a SCHOOL.",
# "Find NOTEBOOK near destination that accepts SOMETHING and has a WASHINGTON.",
# "Find NOTEBOOK near destination that accepts SOMETHING and has a SOMETHING.",
# "Find NOTEBOOK near destination that accepts SOMETHING and has a SCHOOL.",
# "Find NOTEBOOK near destination that accepts SCHOOL and has a WASHINGTON.",
# "Find NOTEBOOK near destination that accepts SCHOOL and has a SOMETHING.",
# "Find NOTEBOOK near destination that accepts SCHOOL and has a SCHOOL.",
#
# "Navigate to WASHINGTON.",
# "Navigate to SOMETHING.",
# "Navigate to SCHOOL.",
# "Navigate to MONALISA.",
# "Navigate to DAVID.",
#
# "What's my WASHINGTON to destination?",
# "What's my SOMETHING to destination?",
# "What's my SCHOOL to destination?",
#
# "Show me alternative WASHINGTON.",
# "Show me alternative SOMETHING.",
# "Show me alternative SCHOOL.",
# "Show me alternative MONALISA.",
#
# "Reroute using WASHINGTON.",
# "Reroute using SOMETHING.",
# "Reroute using SCHOOL.",
# "Reroute using MONALISA.",
#
# "Drive to WASHINGTON.",
# "Drive to SOMETHING.",
# "Drive to SCHOOL.",
# "Drive to MONALISA.",
#
# "What's my WASHINGTON?",
# "What's my SOMETHING?",
# "What's my SCHOOL?",
# "What's my MONALISA?",
#
# "Can I make tomorrow's 10am WASHINGTON without recharging?",
# "Can I make tomorrow's 10am SOMETHING without recharging?",
# "Can I make tomorrow's 10am SCHOOL without recharging?",
# "Can I make tomorrow's 10am MEETING without recharging?",
#
# "What's WASHINGTON like on the WASHINGTON?",
# "What's WASHINGTON like on the SOMETHING?",
# "What's WASHINGTON like on the SCHOOL?",
# "What's WASHINGTON like on the MONALISA?",
#
# "What's SOMETHING like on the WASHINGTON?",
# "What's SOMETHING like on the SOMETHING?",
# "What's SOMETHING like on the SCHOOL?",
# "What's SOMETHING like on the MONALISA?",
#
# "What's SCHOOL like on the WASHINGTON?",
# "What's SCHOOL like on the SOMETHING?",
# "What's SCHOOL like on the SCHOOL?",
# "What's SCHOOL like on the MONALISA?",
#
# "What's MONALISA like on the WASHINGTON?",
# "What's MONALISA like on the SOMETHING?",
# "What's MONALISA like on the SCHOOL?",
# "What's MONALISA like on the MONALISA?",
#
# "Are there any WASHINGTON on my WASHINGTON?",
# "Are there any WASHINGTON on my SOMETHING?",
# "Are there any WASHINGTON on my SCHOOL?",
# "Are there any WASHINGTON on my MONALISA?",
# "Are there any WASHINGTON on my NOTEBOOK?",
#
# "Are there any SOMETHING on my WASHINGTON?",
# "Are there any SOMETHING on my SOMETHING?",
# "Are there any SOMETHING on my SCHOOL?",
# "Are there any SOMETHING on my MONALISA?",
# "Are there any SOMETHING on my NOTEBOOK?",
#
# "Are there any SCHOOL on my WASHINGTON?",
# "Are there any SCHOOL on my SOMETHING?",
# "Are there any SCHOOL on my SCHOOL?",
# "Are there any SCHOOL on my MONALISA?",
# "Are there any SCHOOL on my NOTEBOOK?",
#
# "Are there any MONALISA on my WASHINGTON?",
# "Are there any MONALISA on my SOMETHING?",
# "Are there any MONALISA on my SCHOOL?",
# "Are there any MONALISA on my MONALISA?",
# "Are there any MONALISA on my NOTEBOOK?",
#
# "Are there any NOTEBOOK on my WASHINGTON?",
# "Are there any NOTEBOOK on my SOMETHING?",
# "Are there any NOTEBOOK on my SCHOOL?",
# "Are there any NOTEBOOK on my MONALISA?",
# "Are there any NOTEBOOK on my NOTEBOOK?",
#
# "Will it rain tomorrow in WASHINGTON?",
# "Will it rain tomorrow in SOMETHING?",
# "Will it rain tomorrow in SCHOOL?",
# "Will it rain tomorrow in MEETING?"
# ]
# print("messages2 : ",len(messages2))
#
# scripts=[
# "[SEARCH FROM:WASHINGTON  WHERE:HERE WHEN:AFTERNOON]",
# "[SEARCH FROM:SCHOOL  WHERE:HERE WHEN:AFTERNOON]",
# "[SEARCH FROM:MEETING  WHERE:HERE WHEN:AFTERNOON]",
# "[SEARCH FROM:MONALISA  WHERE:HERE WHEN:AFTERNOON]",
# "[SEARCH FROM:NOTEBOOK  WHERE:HERE WHEN:AFTERNOON]",
# "[SEARCH FROM:SOMETHING  WHERE:HERE WHEN:AFTERNOON]",
#
# "[SEARCH FROM:WASHINGTON  WHERE:WASHINGTON]",
# "[SEARCH FROM:WASHINGTON  WHERE:SOMETHING]",
# "[SEARCH FROM:SOMETHING WHERE:WASHINGTON]",
# "[SEARCH FROM:SOMETHING WHERE:SOMETHING]",
#
# "[SEARCH FROM:WASHINGTON  WHERE:[SEARCH GEOCODE WHERE:WASHINGTON and WASHINGTON]]",
# "[SEARCH FROM:WASHINGTON  WHERE:[SEARCH GEOCODE WHERE:WASHINGTON and SOMETHING]]",
# "[SEARCH FROM:WASHINGTON  WHERE:[SEARCH GEOCODE WHERE:WASHINGTON and SCHOOL]]",
# "[SEARCH FROM:WASHINGTON  WHERE:[SEARCH GEOCODE WHERE:SOMETHING and WASHINGTON]]",
# "[SEARCH FROM:WASHINGTON  WHERE:[SEARCH GEOCODE WHERE:SOMETHING and SCHOOL]]",
# "[SEARCH FROM:WASHINGTON  WHERE:[SEARCH GEOCODE WHERE:SOMETHING and SOMETHING]]",
# "[SEARCH FROM:WASHINGTON  WHERE:[SEARCH GEOCODE WHERE:SCHOOL and WASHINGTON]]",
# "[SEARCH FROM:WASHINGTON  WHERE:[SEARCH GEOCODE WHERE:SCHOOL and SOMETHING]]",
# "[SEARCH FROM:WASHINGTON  WHERE:[SEARCH GEOCODE WHERE:SCHOOL and SCHOOL]]",
#
# "[SEARCH FROM:SOMETHING  WHERE:[SEARCH GEOCODE WHERE:WASHINGTON and WASHINGTON]]",
# "[SEARCH FROM:SOMETHING  WHERE:[SEARCH GEOCODE WHERE:WASHINGTON and SOMETHING]]",
# "[SEARCH FROM:SOMETHING  WHERE:[SEARCH GEOCODE WHERE:WASHINGTON and SCHOOL]]",
# "[SEARCH FROM:SOMETHING  WHERE:[SEARCH GEOCODE WHERE:SOMETHING and WASHINGTON]]",
# "[SEARCH FROM:SOMETHING  WHERE:[SEARCH GEOCODE WHERE:SOMETHING and SCHOOL]]",
# "[SEARCH FROM:SOMETHING  WHERE:[SEARCH GEOCODE WHERE:SOMETHING and SOMETHING]]",
# "[SEARCH FROM:SOMETHING  WHERE:[SEARCH GEOCODE WHERE:SCHOOL and WASHINGTON]]",
# "[SEARCH FROM:SOMETHING  WHERE:[SEARCH GEOCODE WHERE:SCHOOL and SOMETHING]]",
# "[SEARCH FROM:SOMETHING  WHERE:[SEARCH GEOCODE WHERE:SCHOOL and SCHOOL]]",
#
# "[SEARCH FROM:SCHOOL  WHERE:[SEARCH GEOCODE WHERE:WASHINGTON and WASHINGTON]]",
# "[SEARCH FROM:SCHOOL  WHERE:[SEARCH GEOCODE WHERE:WASHINGTON and SOMETHING]]",
# "[SEARCH FROM:SCHOOL  WHERE:[SEARCH GEOCODE WHERE:WASHINGTON and SCHOOL]]",
# "[SEARCH FROM:SCHOOL  WHERE:[SEARCH GEOCODE WHERE:SOMETHING and WASHINGTON]]",
# "[SEARCH FROM:SCHOOL  WHERE:[SEARCH GEOCODE WHERE:SOMETHING and SCHOOL]]",
# "[SEARCH FROM:SCHOOL  WHERE:[SEARCH GEOCODE WHERE:SOMETHING and SOMETHING]]",
# "[SEARCH FROM:SCHOOL  WHERE:[SEARCH GEOCODE WHERE:SCHOOL and WASHINGTON]]",
# "[SEARCH FROM:SCHOOL  WHERE:[SEARCH GEOCODE WHERE:SCHOOL and SOMETHING]]",
# "[SEARCH FROM:SCHOOL  WHERE:[SEARCH GEOCODE WHERE:SCHOOL and SCHOOL]]",
#
# "[SEARCH FROM:WASHINGTON WHERE:NEARBY WITH:WASHINGTON]",
# "[SEARCH FROM:WASHINGTON WHERE:NEARBY WITH:SOMETHING]",
# "[SEARCH FROM:WASHINGTON WHERE:NEARBY WITH:RESTROOM]",
# "[SEARCH FROM:SOMETHING WHERE:NEARBY WITH:WASHINGTON]",
# "[SEARCH FROM:SOMETHING WHERE:NEARBY WITH:SOMETHING]",
# "[SEARCH FROM:SOMETHING WHERE:NEARBY WITH:SCHOOL]",
# "[SEARCH FROM:SCHOOL WHERE:NEARBY WITH:WASHINGTON]",
# "[SEARCH FROM:SCHOOL WHERE:NEARBY WITH:SOMETHING]",
# "[SEARCH FROM:SCHOOL WHERE:NEARBY WITH:SCHOOL]",
#
# "[SEARCH ONE FROM:WASHINGTON WHERE:WASHINGTON]",
# "[SEARCH ONE FROM:WASHINGTON WHERE:SOMETHING]",
# "[SEARCH ONE FROM:WASHINGTON WHERE:SCHOOL]",
# "[SEARCH ONE FROM:SOMETHING WHERE:WASHINGTON]",
# "[SEARCH ONE FROM:SOMETHING WHERE:SOMETHING]",
# "[SEARCH ONE FROM:SOMETHING WHERE:SCHOOL]",
# "[SEARCH ONE FROM:SCHOOL WHERE:WASHINGTON]",
# "[SEARCH ONE FROM:SCHOOLWHERE:SOMETHING]",
# "[SEARCH ONE FROM:SCHOOL WHERE:SCHOOL]",
#
# "[SEARCH ONE FROM:WASHINGTON WHERE:WASHINGTON RANGE:500M WITH:[SORT PRICE ASC]]",
# "[SEARCH ONE FROM:WASHINGTON WHERE:SOMETHING RANGE:500M WITH:[SORT PRICE ASC]]",
# "[SEARCH ONE FROM:WASHINGTON WHERE:SCHOOL RANGE:500M WITH:[SORT PRICE ASC]]",
# "[SEARCH ONE FROM:SOMETHING WHERE:WASHINGTON RANGE:500M WITH:[SORT PRICE ASC]]",
# "[SEARCH ONE FROM:SOMETHING WHERE:SOMETHING RANGE:500M WITH:[SORT PRICE ASC]]",
# "[SEARCH ONE FROM:SOMETHING WHERE:SCHOOL RANGE:500M WITH:[SORT PRICE ASC]]",
# "[SEARCH ONE FROM:SCHOOL WHERE:WASHINGTON RANGE:500M WITH:[SORT PRICE ASC]]",
# "[SEARCH ONE FROM:SCHOOL WHERE:SOMETHING RANGE:500M WITH:[SORT PRICE ASC]]",
# "[SEARCH ONE FROM:SCHOOL WHERE:SCHOOL RANGE:500M WITH:[SORT PRICE ASC]]",
#
# "[SEARCH ONE FROM:WASHINGTON WHERE:WASHINGTON WITH:WASHINGTON]",
# "[SEARCH ONE FROM:WASHINGTON WHERE:WASHINGTON WITH:SOMETHING]",
# "[SEARCH ONE FROM:WASHINGTON WHERE:WASHINGTON WITH:SCHOOL]",
# "[SEARCH ONE FROM:WASHINGTON WHERE:SOMETHING WITH:WASHINGTON]",
# "[SEARCH ONE FROM:WASHINGTON WHERE:SOMETHING WITH:SOMETHING]",
# "[SEARCH ONE FROM:WASHINGTON WHERE:SOMETHING WITH:SCHOOL]",
# "[SEARCH ONE FROM:WASHINGTON WHERE:SCHOOL WITH:WASHINGTON]",
# "[SEARCH ONE FROM:WASHINGTON WHERE:SCHOOL WITH:SOMETHING]",
# "[SEARCH ONE FROM:WASHINGTON WHERE:SCHOOL WITH:SCHOOL]",
#
# "[SEARCH ONE FROM:SOMETHING WHERE:WASHINGTON WITH:WASHINGTON]",
# "[SEARCH ONE FROM:SOMETHING WHERE:WASHINGTON WITH:SOMETHING]",
# "[SEARCH ONE FROM:SOMETHING WHERE:WASHINGTON WITH:SCHOOL]",
# "[SEARCH ONE FROM:SOMETHING WHERE:SOMETHING WITH:WASHINGTON]",
# "[SEARCH ONE FROM:SOMETHING WHERE:SOMETHING WITH:SOMETHING]",
# "[SEARCH ONE FROM:SOMETHING WHERE:SOMETHING WITH:SCHOOL]",
# "[SEARCH ONE FROM:SOMETHING WHERE:SCHOOL WITH:WASHINGTON]",
# "[SEARCH ONE FROM:SOMETHING WHERE:SCHOOL WITH:SOMETHING]",
# "[SEARCH ONE FROM:SOMETHING WHERE:SCHOOL WITH:SCHOOL]",
#
# "[SEARCH ONE FROM:SCHOOL WHERE:WASHINGTON WITH:WASHINGTON]",
# "[SEARCH ONE FROM:SCHOOL WHERE:WASHINGTON WITH:SOMETHING]",
# "[SEARCH ONE FROM:SCHOOL WHERE:WASHINGTON WITH:SCHOOL]",
# "[SEARCH ONE FROM:SCHOOL WHERE:SOMETHING WITH:WASHINGTON]",
# "[SEARCH ONE FROM:SCHOOL WHERE:SOMETHING WITH:SOMETHING]",
# "[SEARCH ONE FROM:SCHOOL WHERE:SOMETHING WITH:SCHOOL]",
# "[SEARCH ONE FROM:SCHOOL WHERE:SCHOOL WITH:WASHINGTON]",
# "[SEARCH ONE FROM:SCHOOL WHERE:SCHOOL WITH:SOMETHING]",
# "[SEARCH ONE FROM:SCHOOL WHERE:SCHOOL WITH:SCHOOL]",
#
# "[SEARCH ONE FROM:WASHINGTON WITH:WASHINGTON WITH:WASHINGTON]",
# "[SEARCH ONE FROM:WASHINGTON WITH:WASHINGTON WITH:SOMETHING]",
# "[SEARCH ONE FROM:WASHINGTON WITH:WASHINGTON WITH:SCHOOL]",
# "[SEARCH ONE FROM:WASHINGTON WITH:SOMETHING WITH:WASHINGTON]",
# "[SEARCH ONE FROM:WASHINGTON WITH:SOMETHING WITH:SOMETHING]",
# "[SEARCH ONE FROM:WASHINGTON WITH:SOMETHING WITH:SCHOOL]",
# "[SEARCH ONE FROM:WASHINGTON WITH:SCHOOL WITH:WASHINGTON]",
# "[SEARCH ONE FROM:WASHINGTON WITH:SCHOOL WITH:SOMETHING]",
# "[SEARCH ONE FROM:WASHINGTON WITH:SCHOOL WITH:SCHOOL]",
#
# "[SEARCH ONE FROM:SOMETHING WITH:WASHINGTON WITH:WASHINGTON]",
# "[SEARCH ONE FROM:SOMETHING WITH:WASHINGTON WITH:SOMETHING]",
# "[SEARCH ONE FROM:SOMETHING WITH:WASHINGTON WITH:SCHOOL]",
# "[SEARCH ONE FROM:SOMETHING WITH:SOMETHING WITH:WASHINGTON]",
# "[SEARCH ONE FROM:SOMETHING WITH:SOMETHING WITH:SOMETHING]",
# "[SEARCH ONE FROM:SOMETHING WITH:SOMETHING WITH:SCHOOL]",
# "[SEARCH ONE FROM:SOMETHING WITH:SCHOOL WITH:WASHINGTON]",
# "[SEARCH ONE FROM:SOMETHING WITH:SCHOOL WITH:SOMETHING]",
# "[SEARCH ONE FROM:SOMETHING WITH:SCHOOL WITH:SCHOOL]",
#
# "[SEARCH ONE FROM:SCHOOL WITH:WASHINGTON WITH:WASHINGTON]",
# "[SEARCH ONE FROM:SCHOOL WITH:WASHINGTON WITH:SOMETHING]",
# "[SEARCH ONE FROM:SCHOOL WITH:WASHINGTON WITH:SCHOOL]",
# "[SEARCH ONE FROM:SCHOOL WITH:SOMETHING WITH:WASHINGTON]",
# "[SEARCH ONE FROM:SCHOOL WITH:SOMETHING WITH:SOMETHING]",
# "[SEARCH ONE FROM:SCHOOL WITH:SOMETHING WITH:SCHOOL]",
# "[SEARCH ONE FROM:SCHOOL WITH:SCHOOL WITH:WASHINGTON]",
# "[SEARCH ONE FROM:SCHOOL WITH:SCHOOL WITH:SOMETHING]",
# "[SEARCH ONE FROM:SCHOOL WITH:SCHOOL WITH:SCHOOL]",
#
# "[SEARCH ONE FROM:MONALISA WITH:WASHINGTON WITH:WASHINGTON]",
# "[SEARCH ONE FROM:MONALISA WITH:WASHINGTON WITH:SOMETHING]",
# "[SEARCH ONE FROM:MONALISA WITH:WASHINGTON WITH:SCHOOL]",
# "[SEARCH ONE FROM:MONALISA WITH:SOMETHING WITH:WASHINGTON]",
# "[SEARCH ONE FROM:MONALISA WITH:SOMETHING WITH:SOMETHING]",
# "[SEARCH ONE FROM:MONALISA WITH:SOMETHING WITH:SCHOOL]",
# "[SEARCH ONE FROM:MONALISA WITH:SCHOOL WITH:WASHINGTON]",
# "[SEARCH ONE FROM:MONALISA WITH:SCHOOL WITH:SOMETHING]",
# "[SEARCH ONE FROM:MONALISA WITH:SCHOOL WITH:SCHOOL]",
#
# "[SEARCH ONE FROM:NOTEBOOK WITH:WASHINGTON WITH:WASHINGTON]",
# "[SEARCH ONE FROM:NOTEBOOK WITH:WASHINGTON WITH:SOMETHING]",
# "[SEARCH ONE FROM:NOTEBOOK WITH:WASHINGTON WITH:SCHOOL]",
# "[SEARCH ONE FROM:NOTEBOOK WITH:SOMETHING WITH:WASHINGTON]",
# "[SEARCH ONE FROM:NOTEBOOK WITH:SOMETHING WITH:SOMETHING]",
# "[SEARCH ONE FROM:NOTEBOOK WITH:SOMETHING WITH:SCHOOL]",
# "[SEARCH ONE FROM:NOTEBOOK WITH:SCHOOL WITH:WASHINGTON]",
# "[SEARCH ONE FROM:NOTEBOOK WITH:SCHOOL WITH:SOMETHING]",
# "[SEARCH ONE FROM:NOTEBOOK WITH:SCHOOL WITH:SCHOOL]",
#
# "[ROUTE TO:[SEARCH KEYWORD:WASHINGTON]]",
# "[ROUTE TO:[SEARCH KEYWORD:SOMETHING]]",
# "[ROUTE TO:[SEARCH KEYWORD:SCHOOL]]",
# "[ROUTE TO:[SEARCH KEYWORD:MONALISA]]",
# "[ROUTE TO:[SEARCH KEYWORD:DAVID]]",
#
# "[ROUTE INFO:WASHINGTON]",
# "[ROUTE INFO:SOMETHING]",
# "[ROUTE INFO:SCHOOL]",
#
# "[ROUTE WASHINGTON]",
# "[ROUTE SOMETHING]",
# "[ROUTE SCHOOL]",
# "[ROUTE MONALISA]",
#
# "[ROUTE ALTROUTE USE:[SEARCH LINKS:WASHINGTON]]",
# "[ROUTE ALTROUTE USE:[SEARCH LINKS:SOMETHING]]",
# "[ROUTE ALTROUTE USE:[SEARCH LINKS:SCHOOL]]",
# "[ROUTE ALTROUTE USE:[SEARCH LINKS:MONALISA]]",
#
# "[MODE GUIDANCE WITH:[ROUTE TO:[SEARCH KEYWORD:WASHINGTON]]]",
# "[MODE GUIDANCE WITH:[ROUTE TO:[SEARCH KEYWORD:SOMETHING]]]",
# "[MODE GUIDANCE WITH:[ROUTE TO:[SEARCH KEYWORD:SCHOOL]]]",
# "[MODE GUIDANCE WITH:[ROUTE TO:[SEARCH KEYWORD:MONALISA]]",
#
# "[MODE WASHINGTON]",
# "[MODE SOMETHING]",
# "[MODE SCHOOL]",
# "[MODE MONALISA]",
#
# "[MODE DRIVERANGE TO:[SEARCH KEYWORD:WASHINGTON FROM:SCHEDULE WHEN:10AM] WITH:[VOICERESPONSE TEMPLATE:YES/NO*]]",
# "[MODE DRIVERANGE TO:[SEARCH KEYWORD:SOMETHING FROM:SCHEDULE WHEN:10AM] WITH:[VOICERESPONSE TEMPLATE:YES/NO*]]",
# "[MODE DRIVERANGE TO:[SEARCH KEYWORD:SCHOOL FROM:SCHEDULE WHEN:10AM] WITH:[VOICERESPONSE TEMPLATE:YES/NO*]]",
# "[MODE DRIVERANGE TO:[SEARCH KEYWORD:MEETING FROM:SCHEDULE WHEN:10AM] WITH:[VOICERESPONSE TEMPLATE:YES/NO*]]",
#
# "[MODE TRAFFIC [SEARCH FROM:WASHINGTON WHERE:[SEARCH KEYWORD:WASHINGTON]] WITH:[VOICERESPONSE TEMPLATE:””*]",
# "[MODE TRAFFIC [SEARCH FROM:WASHINGTON WHERE:[SEARCH KEYWORD:SOMETHING]] WITH:[VOICERESPONSE TEMPLATE:””*]",
# "[MODE TRAFFIC [SEARCH FROM:WASHINGTON WHERE:[SEARCH KEYWORD:SCHOOL]] WITH:[VOICERESPONSE TEMPLATE:””*]",
# "[MODE TRAFFIC [SEARCH FROM:WASHINGTON WHERE:[SEARCH KEYWORD:MONALISA]] WITH:[VOICERESPONSE TEMPLATE:””*]",
#
# "[MODE TRAFFIC [SEARCH FROM:SOMETHING WHERE:[SEARCH KEYWORD:WASHINGTON]] WITH:[VOICERESPONSE TEMPLATE:””*]",
# "[MODE TRAFFIC [SEARCH FROM:SOMETHING WHERE:[SEARCH KEYWORD:SOMETHING]] WITH:[VOICERESPONSE TEMPLATE:””*]",
# "[MODE TRAFFIC [SEARCH FROM:SOMETHING WHERE:[SEARCH KEYWORD:SCHOOL]] WITH:[VOICERESPONSE TEMPLATE:””*]",
# "[MODE TRAFFIC [SEARCH FROM:SOMETHING WHERE:[SEARCH KEYWORD:MONALISA]] WITH:[VOICERESPONSE TEMPLATE:””*]",
#
# "[MODE TRAFFIC [SEARCH FROM:SCHOOL WHERE:[SEARCH KEYWORD:WASHINGTON]] WITH:[VOICERESPONSE TEMPLATE:””*]",
# "[MODE TRAFFIC [SEARCH FROM:SCHOOL WHERE:[SEARCH KEYWORD:SOMETHING]] WITH:[VOICERESPONSE TEMPLATE:””*]",
# "[MODE TRAFFIC [SEARCH FROM:SCHOOL WHERE:[SEARCH KEYWORD:SCHOOL]] WITH:[VOICERESPONSE TEMPLATE:””*]",
# "[MODE TRAFFIC [SEARCH FROM:SCHOOL WHERE:[SEARCH KEYWORD:MONALISA]] WITH:[VOICERESPONSE TEMPLATE:””*]",
#
# "[MODE TRAFFIC [SEARCH FROM:MONALISA WHERE:[SEARCH KEYWORD:WASHINGTON]] WITH:[VOICERESPONSE TEMPLATE:””*]",
# "[MODE TRAFFIC [SEARCH FROM:MONALISA WHERE:[SEARCH KEYWORD:SOMETHING]] WITH:[VOICERESPONSE TEMPLATE:””*]",
# "[MODE TRAFFIC [SEARCH FROM:MONALISA WHERE:[SEARCH KEYWORD:SCHOOL]] WITH:[VOICERESPONSE TEMPLATE:””*]",
# "[MODE TRAFFIC [SEARCH FROM:MONALISA WHERE:[SEARCH KEYWORD:MONALISA]] WITH:[VOICERESPONSE TEMPLATE:””*]",
#
# "[MODE WASHINGTON WHERE:WASHINGTON WITH:[VOICERESPONSE TEMPLATE:””*]]",
# "[MODE WASHINGTON WHERE:SOMETHING WITH:[VOICERESPONSE TEMPLATE:””*]]",
# "[MODE WASHINGTON WHERE:SCHOOL WITH:[VOICERESPONSE TEMPLATE:””*]]",
# "[MODE WASHINGTON WHERE:MONALISA WITH:[VOICERESPONSE TEMPLATE:””*]]",
# "[MODE WASHINGTON WHERE:NOTEBOOK WITH:[VOICERESPONSE TEMPLATE:””*]]",
#
# "[MODE SOMETHING WHERE:WASHINGTON WITH:[VOICERESPONSE TEMPLATE:””*]]",
# "[MODE SOMETHING WHERE:SOMETHING WITH:[VOICERESPONSE TEMPLATE:””*]]",
# "[MODE SOMETHING WHERE:SCHOOL WITH:[VOICERESPONSE TEMPLATE:””*]]",
# "[MODE SOMETHING WHERE:MONALISA WITH:[VOICERESPONSE TEMPLATE:””*]]",
# "[MODE SOMETHING WHERE:NOTEBOOK WITH:[VOICERESPONSE TEMPLATE:””*]]",
#
# "[MODE SCHOOL WHERE:WASHINGTON WITH:[VOICERESPONSE TEMPLATE:””*]]",
# "[MODE SCHOOL WHERE:SOMETHING WITH:[VOICERESPONSE TEMPLATE:””*]]",
# "[MODE SCHOOL WHERE:SCHOOL WITH:[VOICERESPONSE TEMPLATE:””*]]",
# "[MODE SCHOOL WHERE:MONALISA WITH:[VOICERESPONSE TEMPLATE:””*]]",
# "[MODE SCHOOL WHERE:NOTEBOOK WITH:[VOICERESPONSE TEMPLATE:””*]]",
#
# "[MODE MONALISA WHERE:WASHINGTON WITH:[VOICERESPONSE TEMPLATE:””*]]",
# "[MODE MONALISA WHERE:SOMETHING WITH:[VOICERESPONSE TEMPLATE:””*]]",
# "[MODE MONALISA WHERE:SCHOOL WITH:[VOICERESPONSE TEMPLATE:””*]]",
# "[MODE MONALISA WHERE:MONALISA WITH:[VOICERESPONSE TEMPLATE:””*]]",
# "[MODE MONALISA WHERE:NOTEBOOK WITH:[VOICERESPONSE TEMPLATE:””*]]",
#
# "[MODE NOTEBOOK WHERE:WASHINGTON WITH:[VOICERESPONSE TEMPLATE:””*]]",
# "[MODE NOTEBOOK WHERE:SOMETHING WITH:[VOICERESPONSE TEMPLATE:””*]]",
# "[MODE NOTEBOOK WHERE:SCHOOL WITH:[VOICERESPONSE TEMPLATE:””*]]",
# "[MODE NOTEBOOK WHERE:MONALISA WITH:[VOICERESPONSE TEMPLATE:””*]]",
# "[MODE NOTEBOOK WHERE:NOTEBOOK WITH:[VOICERESPONSE TEMPLATE:””*]]",
#
# "[MODE WEATHERFORECAST WHERE:[SEARCH KEYWORD:WASHINGTON] WHEN:TOMORROW]",
# "[MODE WEATHERFORECAST WHERE:[SEARCH KEYWORD:SOMETHING] WHEN:TOMORROW]",
# "[MODE WEATHERFORECAST WHERE:[SEARCH KEYWORD:SCHOOL] WHEN:TOMORROW]",
# "[MODE WEATHERFORECAST WHERE:[SEARCH KEYWORD:MEETING] WHEN:TOMORROW]"
# ]
#
# print("scripts: ",len(scripts))

one =[
    "What's the WASHINGTON for this Time?",
    "What's the SCHOOL for this Time?",
    "What's the MEETING for this Time?",
    "What's the MONALISA for this Time?",
    "What's the NOTEBOOK for this Time?",
    "What's the SOMETHING for this Time?",

    "Navigate to WASHINGTON.",
    "Navigate to SOMETHING.",
    "Navigate to SCHOOL.",
    "Navigate to MONALISA.",
    "Navigate to DAVID.",

    "What's my WASHINGTON to destination?",
    "What's my SOMETHING to destination?",
    "What's my SCHOOL to destination?",

    "Show me alternative WASHINGTON.",
    "Show me alternative SOMETHING.",
    "Show me alternative SCHOOL.",
    "Show me alternative MONALISA.",

    "Reroute using WASHINGTON.",
    "Reroute using SOMETHING.",
    "Reroute using SCHOOL.",
    "Reroute using MONALISA.",

    "Drive to WASHINGTON.",
    "Drive to SOMETHING.",
    "Drive to SCHOOL.",
    "Drive to MONALISA.",

    "What's my WASHINGTON?",
    "What's my SOMETHING?",
    "What's my SCHOOL?",
    "What's my MONALISA?",

    "Can I make Time's 10am WASHINGTON without recharging?",
    "Can I make Time's 10am SOMETHING without recharging?",
    "Can I make Time's 10am SCHOOL without recharging?",
    "Can I make Time's 10am MEETING without recharging?",

    "Will it rain Time in WASHINGTON?",
    "Will it rain Time in SOMETHING?",
    "Will it rain Time in SCHOOL?",
    "Will it rain Time in MEETING?"
]
one_script = [
    "[SEARCH FROM:WASHINGTON  WHERE:HERE WHEN:Time]",
    "[SEARCH FROM:SCHOOL  WHERE:HERE WHEN:Time]",
    "[SEARCH FROM:MEETING  WHERE:HERE WHEN:Time]",
    "[SEARCH FROM:MONALISA  WHERE:HERE WHEN:Time]",
    "[SEARCH FROM:NOTEBOOK  WHERE:HERE WHEN:Time]",
    "[SEARCH FROM:SOMETHING  WHERE:HERE WHEN:Time]",

    "[ROUTE TO:[SEARCH KEYWORD:WASHINGTON]]",
    "[ROUTE TO:[SEARCH KEYWORD:SOMETHING]]",
    "[ROUTE TO:[SEARCH KEYWORD:SCHOOL]]",
    "[ROUTE TO:[SEARCH KEYWORD:MONALISA]]",
    "[ROUTE TO:[SEARCH KEYWORD:DAVID]]",

    "[ROUTE INFO:WASHINGTON]",
    "[ROUTE INFO:SOMETHING]",
    "[ROUTE INFO:SCHOOL]",

    "[ROUTE WASHINGTON]",
    "[ROUTE SOMETHING]",
    "[ROUTE SCHOOL]",
    "[ROUTE MONALISA]",

    "[ROUTE ALTROUTE USE:[SEARCH LINKS:WASHINGTON]]",
    "[ROUTE ALTROUTE USE:[SEARCH LINKS:SOMETHING]]",
    "[ROUTE ALTROUTE USE:[SEARCH LINKS:SCHOOL]]",
    "[ROUTE ALTROUTE USE:[SEARCH LINKS:MONALISA]]",

    "[MODE GUIDANCE WITH:[ROUTE TO:[SEARCH KEYWORD:WASHINGTON]]]",
    "[MODE GUIDANCE WITH:[ROUTE TO:[SEARCH KEYWORD:SOMETHING]]]",
    "[MODE GUIDANCE WITH:[ROUTE TO:[SEARCH KEYWORD:SCHOOL]]]",
    "[MODE GUIDANCE WITH:[ROUTE TO:[SEARCH KEYWORD:MONALISA]]",

    "[MODE WASHINGTON]",
    "[MODE SOMETHING]",
    "[MODE SCHOOL]",
    "[MODE MONALISA]",

    "[MODE DRIVERANGE TO:[SEARCH KEYWORD:WASHINGTON FROM:SCHEDULE WHEN:10AM] WITH:[VOICERESPONSE TEMPLATE:YES/NO*]]",
    "[MODE DRIVERANGE TO:[SEARCH KEYWORD:SOMETHING FROM:SCHEDULE WHEN:10AM] WITH:[VOICERESPONSE TEMPLATE:YES/NO*]]",
    "[MODE DRIVERANGE TO:[SEARCH KEYWORD:SCHOOL FROM:SCHEDULE WHEN:10AM] WITH:[VOICERESPONSE TEMPLATE:YES/NO*]]",
    "[MODE DRIVERANGE TO:[SEARCH KEYWORD:MEETING FROM:SCHEDULE WHEN:10AM] WITH:[VOICERESPONSE TEMPLATE:YES/NO*]]",

    "[MODE WEATHERFORECAST WHERE:[SEARCH KEYWORD:WASHINGTON] WHEN:Time]",
    "[MODE WEATHERFORECAST WHERE:[SEARCH KEYWORD:SOMETHING] WHEN:Time]",
    "[MODE WEATHERFORECAST WHERE:[SEARCH KEYWORD:SCHOOL] WHEN:Time]",
    "[MODE WEATHERFORECAST WHERE:[SEARCH KEYWORD:MEETING] WHEN:Time]"
]
two = [
    "What's the WASHINGTON like on my WASHINGTON?",
    "What's the WASHINGTON like on my SOMETHING?",
    "What's the SOMETHING like on my WASHINGTON?",
    "What's the SOMETHING like on my SOMETHING?",

    "Can you find me a WASHINGTON with WASHINGTON nearby?",
    "Can you find me a WASHINGTON with SOMETHING nearby?",
    "Can you find me a WASHINGTON with SCHOOL nearby?",
    "Can you find me a SOMETHING with WASHINGTON nearby?",
    "Can you find me a SOMETHING with SOMETHING nearby?",
    "Can you find me a SOMETHING with SCHOOL nearby?",
    "Can you find me a SCHOOL with WASHINGTON nearby?",
    "Can you find me a SCHOOL with SOMETHING nearby?",
    "Can you find me a SCHOOL with SCHOOL nearby?",

    "Find a WASHINGTON along WASHINGTON.",
    "Find a WASHINGTON along SOMETHING.",
    "Find a WASHINGTON along SCHOOL.",
    "Find a SOMETHING along WASHINGTON.",
    "Find a SOMETHING along SOMETHING.",
    "Find a SOMETHING along SCHOOL.",
    "Find a SCHOOL along WASHINGTON.",
    "Find a SCHOOL along SOMETHING.",
    "Find a SCHOOL along SCHOOL.",

    "Find the cheapest indoor WASHINGTON within 500 meters of my WASHINGTON.",
    "Find the cheapest indoor WASHINGTON within 500 meters of my SOMETHING.",
    "Find the cheapest indoor WASHINGTON within 500 meters of my SCHOOL.",
    "Find the cheapest indoor SOMETHING within 500 meters of my WASHINGTON.",
    "Find the cheapest indoor SOMETHING within 500 meters of my SOMETHING.",
    "Find the cheapest indoor SOMETHING within 500 meters of my SCHOOL.",
    "Find the cheapest indoor SCHOOL within 500 meters of my WASHINGTON.",
    "Find the cheapest indoor SCHOOL within 500 meters of my SOMETHING.",
    "Find the cheapest indoor SCHOOL within 500 meters of my SCHOOL.",

    "What's WASHINGTON like on the WASHINGTON?",
    "What's WASHINGTON like on the SOMETHING?",
    "What's WASHINGTON like on the SCHOOL?",
    "What's WASHINGTON like on the MONALISA?",

    "What's SOMETHING like on the WASHINGTON?",
    "What's SOMETHING like on the SOMETHING?",
    "What's SOMETHING like on the SCHOOL?",
    "What's SOMETHING like on the MONALISA?",

    "What's SCHOOL like on the WASHINGTON?",
    "What's SCHOOL like on the SOMETHING?",
    "What's SCHOOL like on the SCHOOL?",
    "What's SCHOOL like on the MONALISA?",

    "What's MONALISA like on the WASHINGTON?",
    "What's MONALISA like on the SOMETHING?",
    "What's MONALISA like on the SCHOOL?",
    "What's MONALISA like on the MONALISA?",

    "Are there any WASHINGTON on my WASHINGTON?",
    "Are there any WASHINGTON on my SOMETHING?",
    "Are there any WASHINGTON on my SCHOOL?",
    "Are there any WASHINGTON on my MONALISA?",
    "Are there any WASHINGTON on my NOTEBOOK?",

    "Are there any SOMETHING on my WASHINGTON?",
    "Are there any SOMETHING on my SOMETHING?",
    "Are there any SOMETHING on my SCHOOL?",
    "Are there any SOMETHING on my MONALISA?",
    "Are there any SOMETHING on my NOTEBOOK?",

    "Are there any SCHOOL on my WASHINGTON?",
    "Are there any SCHOOL on my SOMETHING?",
    "Are there any SCHOOL on my SCHOOL?",
    "Are there any SCHOOL on my MONALISA?",
    "Are there any SCHOOL on my NOTEBOOK?",

    "Are there any MONALISA on my WASHINGTON?",
    "Are there any MONALISA on my SOMETHING?",
    "Are there any MONALISA on my SCHOOL?",
    "Are there any MONALISA on my MONALISA?",
    "Are there any MONALISA on my NOTEBOOK?",

    "Are there any NOTEBOOK on my WASHINGTON?",
    "Are there any NOTEBOOK on my SOMETHING?",
    "Are there any NOTEBOOK on my SCHOOL?",
    "Are there any NOTEBOOK on my MONALISA?",
    "Are there any NOTEBOOK on my NOTEBOOK?"

]
two_script = [
    "[SEARCH FROM:WASHINGTON  WHERE:WASHINGTON]",
    "[SEARCH FROM:WASHINGTON  WHERE:SOMETHING]",
    "[SEARCH FROM:SOMETHING WHERE:WASHINGTON]",
    "[SEARCH FROM:SOMETHING WHERE:SOMETHING]",

    "[SEARCH FROM:WASHINGTON WHERE:NEARBY WITH:WASHINGTON]",
    "[SEARCH FROM:WASHINGTON WHERE:NEARBY WITH:SOMETHING]",
    "[SEARCH FROM:WASHINGTON WHERE:NEARBY WITH:RESTROOM]",
    "[SEARCH FROM:SOMETHING WHERE:NEARBY WITH:WASHINGTON]",
    "[SEARCH FROM:SOMETHING WHERE:NEARBY WITH:SOMETHING]",
    "[SEARCH FROM:SOMETHING WHERE:NEARBY WITH:SCHOOL]",
    "[SEARCH FROM:SCHOOL WHERE:NEARBY WITH:WASHINGTON]",
    "[SEARCH FROM:SCHOOL WHERE:NEARBY WITH:SOMETHING]",
    "[SEARCH FROM:SCHOOL WHERE:NEARBY WITH:SCHOOL]",

    "[SEARCH ONE FROM:WASHINGTON WHERE:WASHINGTON]",
    "[SEARCH ONE FROM:WASHINGTON WHERE:SOMETHING]",
    "[SEARCH ONE FROM:WASHINGTON WHERE:SCHOOL]",
    "[SEARCH ONE FROM:SOMETHING WHERE:WASHINGTON]",
    "[SEARCH ONE FROM:SOMETHING WHERE:SOMETHING]",
    "[SEARCH ONE FROM:SOMETHING WHERE:SCHOOL]",
    "[SEARCH ONE FROM:SCHOOL WHERE:WASHINGTON]",
    "[SEARCH ONE FROM:SCHOOLWHERE:SOMETHING]",
    "[SEARCH ONE FROM:SCHOOL WHERE:SCHOOL]",

    "[SEARCH ONE FROM:WASHINGTON WHERE:WASHINGTON RANGE:500M WITH:[SORT PRICE ASC]]",
    "[SEARCH ONE FROM:WASHINGTON WHERE:SOMETHING RANGE:500M WITH:[SORT PRICE ASC]]",
    "[SEARCH ONE FROM:WASHINGTON WHERE:SCHOOL RANGE:500M WITH:[SORT PRICE ASC]]",
    "[SEARCH ONE FROM:SOMETHING WHERE:WASHINGTON RANGE:500M WITH:[SORT PRICE ASC]]",
    "[SEARCH ONE FROM:SOMETHING WHERE:SOMETHING RANGE:500M WITH:[SORT PRICE ASC]]",
    "[SEARCH ONE FROM:SOMETHING WHERE:SCHOOL RANGE:500M WITH:[SORT PRICE ASC]]",
    "[SEARCH ONE FROM:SCHOOL WHERE:WASHINGTON RANGE:500M WITH:[SORT PRICE ASC]]",
    "[SEARCH ONE FROM:SCHOOL WHERE:SOMETHING RANGE:500M WITH:[SORT PRICE ASC]]",
    "[SEARCH ONE FROM:SCHOOL WHERE:SCHOOL RANGE:500M WITH:[SORT PRICE ASC]]",

    "[MODE TRAFFIC [SEARCH FROM:WASHINGTON WHERE:[SEARCH KEYWORD:WASHINGTON]] WITH:[VOICERESPONSE TEMPLATE:””*]",
    "[MODE TRAFFIC [SEARCH FROM:WASHINGTON WHERE:[SEARCH KEYWORD:SOMETHING]] WITH:[VOICERESPONSE TEMPLATE:””*]",
    "[MODE TRAFFIC [SEARCH FROM:WASHINGTON WHERE:[SEARCH KEYWORD:SCHOOL]] WITH:[VOICERESPONSE TEMPLATE:””*]",
    "[MODE TRAFFIC [SEARCH FROM:WASHINGTON WHERE:[SEARCH KEYWORD:MONALISA]] WITH:[VOICERESPONSE TEMPLATE:””*]",

    "[MODE TRAFFIC [SEARCH FROM:SOMETHING WHERE:[SEARCH KEYWORD:WASHINGTON]] WITH:[VOICERESPONSE TEMPLATE:””*]",
    "[MODE TRAFFIC [SEARCH FROM:SOMETHING WHERE:[SEARCH KEYWORD:SOMETHING]] WITH:[VOICERESPONSE TEMPLATE:””*]",
    "[MODE TRAFFIC [SEARCH FROM:SOMETHING WHERE:[SEARCH KEYWORD:SCHOOL]] WITH:[VOICERESPONSE TEMPLATE:””*]",
    "[MODE TRAFFIC [SEARCH FROM:SOMETHING WHERE:[SEARCH KEYWORD:MONALISA]] WITH:[VOICERESPONSE TEMPLATE:””*]",

    "[MODE TRAFFIC [SEARCH FROM:SCHOOL WHERE:[SEARCH KEYWORD:WASHINGTON]] WITH:[VOICERESPONSE TEMPLATE:””*]",
    "[MODE TRAFFIC [SEARCH FROM:SCHOOL WHERE:[SEARCH KEYWORD:SOMETHING]] WITH:[VOICERESPONSE TEMPLATE:””*]",
    "[MODE TRAFFIC [SEARCH FROM:SCHOOL WHERE:[SEARCH KEYWORD:SCHOOL]] WITH:[VOICERESPONSE TEMPLATE:””*]",
    "[MODE TRAFFIC [SEARCH FROM:SCHOOL WHERE:[SEARCH KEYWORD:MONALISA]] WITH:[VOICERESPONSE TEMPLATE:””*]",

    "[MODE TRAFFIC [SEARCH FROM:MONALISA WHERE:[SEARCH KEYWORD:WASHINGTON]] WITH:[VOICERESPONSE TEMPLATE:””*]",
    "[MODE TRAFFIC [SEARCH FROM:MONALISA WHERE:[SEARCH KEYWORD:SOMETHING]] WITH:[VOICERESPONSE TEMPLATE:””*]",
    "[MODE TRAFFIC [SEARCH FROM:MONALISA WHERE:[SEARCH KEYWORD:SCHOOL]] WITH:[VOICERESPONSE TEMPLATE:””*]",
    "[MODE TRAFFIC [SEARCH FROM:MONALISA WHERE:[SEARCH KEYWORD:MONALISA]] WITH:[VOICERESPONSE TEMPLATE:””*]",

    "[MODE WASHINGTON WHERE:WASHINGTON WITH:[VOICERESPONSE TEMPLATE:””*]]",
    "[MODE WASHINGTON WHERE:SOMETHING WITH:[VOICERESPONSE TEMPLATE:””*]]",
    "[MODE WASHINGTON WHERE:SCHOOL WITH:[VOICERESPONSE TEMPLATE:””*]]",
    "[MODE WASHINGTON WHERE:MONALISA WITH:[VOICERESPONSE TEMPLATE:””*]]",
    "[MODE WASHINGTON WHERE:NOTEBOOK WITH:[VOICERESPONSE TEMPLATE:””*]]",

    "[MODE SOMETHING WHERE:WASHINGTON WITH:[VOICERESPONSE TEMPLATE:””*]]",
    "[MODE SOMETHING WHERE:SOMETHING WITH:[VOICERESPONSE TEMPLATE:””*]]",
    "[MODE SOMETHING WHERE:SCHOOL WITH:[VOICERESPONSE TEMPLATE:””*]]",
    "[MODE SOMETHING WHERE:MONALISA WITH:[VOICERESPONSE TEMPLATE:””*]]",
    "[MODE SOMETHING WHERE:NOTEBOOK WITH:[VOICERESPONSE TEMPLATE:””*]]",

    "[MODE SCHOOL WHERE:WASHINGTON WITH:[VOICERESPONSE TEMPLATE:””*]]",
    "[MODE SCHOOL WHERE:SOMETHING WITH:[VOICERESPONSE TEMPLATE:””*]]",
    "[MODE SCHOOL WHERE:SCHOOL WITH:[VOICERESPONSE TEMPLATE:””*]]",
    "[MODE SCHOOL WHERE:MONALISA WITH:[VOICERESPONSE TEMPLATE:””*]]",
    "[MODE SCHOOL WHERE:NOTEBOOK WITH:[VOICERESPONSE TEMPLATE:””*]]",

    "[MODE MONALISA WHERE:WASHINGTON WITH:[VOICERESPONSE TEMPLATE:””*]]",
    "[MODE MONALISA WHERE:SOMETHING WITH:[VOICERESPONSE TEMPLATE:””*]]",
    "[MODE MONALISA WHERE:SCHOOL WITH:[VOICERESPONSE TEMPLATE:””*]]",
    "[MODE MONALISA WHERE:MONALISA WITH:[VOICERESPONSE TEMPLATE:””*]]",
    "[MODE MONALISA WHERE:NOTEBOOK WITH:[VOICERESPONSE TEMPLATE:””*]]",

    "[MODE NOTEBOOK WHERE:WASHINGTON WITH:[VOICERESPONSE TEMPLATE:””*]]",
    "[MODE NOTEBOOK WHERE:SOMETHING WITH:[VOICERESPONSE TEMPLATE:””*]]",
    "[MODE NOTEBOOK WHERE:SCHOOL WITH:[VOICERESPONSE TEMPLATE:””*]]",
    "[MODE NOTEBOOK WHERE:MONALISA WITH:[VOICERESPONSE TEMPLATE:””*]]",
    "[MODE NOTEBOOK WHERE:NOTEBOOK WITH:[VOICERESPONSE TEMPLATE:””*]]"
]
three = [
    "Show me a WASHINGTON on WASHINGTON and WASHINGTON.",
    "Show me a WASHINGTON on WASHINGTON and SOMETHING.",
    "Show me a WASHINGTON on WASHINGTON and SCHOOL.",
    "Show me a WASHINGTON on SOMETHING and WASHINGTON.",
    "Show me a WASHINGTON on SOMETHING and SCHOOL.",
    "Show me a WASHINGTON on SOMETHING and SOMETHING.",
    "Show me a WASHINGTON on SCHOOL and WASHINGTON.",
    "Show me a WASHINGTON on SCHOOL and SOMETHING.",
    "Show me a WASHINGTON on SCHOOL and SCHOOL.",

    "Show me a SOMETHING on WASHINGTON and WASHINGTON.",
    "Show me a SOMETHING on WASHINGTON and SOMETHING.",
    "Show me a SOMETHING on WASHINGTON and SCHOOL.",
    "Show me a SOMETHING on SOMETHING and WASHINGTON.",
    "Show me a SOMETHING on SOMETHING and SCHOOL.",
    "Show me a SOMETHING on SOMETHING and SOMETHING.",
    "Show me a SOMETHING on SCHOOL and WASHINGTON.",
    "Show me a SOMETHING on SCHOOL and SOMETHING.",
    "Show me a SOMETHING on SCHOOL and SCHOOL.",

    "Show me a SCHOOL on WASHINGTON and WASHINGTON.",
    "Show me a SCHOOL on WASHINGTON and SOMETHING.",
    "Show me a SCHOOL on WASHINGTON and SCHOOL.",
    "Show me a SCHOOL on SOMETHING and WASHINGTON.",
    "Show me a SCHOOL on SOMETHING and SCHOOL.",
    "Show me a SCHOOL on SOMETHING and SOMETHING.",
    "Show me a SCHOOL on SCHOOL and WASHINGTON.",
    "Show me a SCHOOL on SCHOOL and SOMETHING.",
    "Show me a SCHOOL on SCHOOL and SCHOOL.",

    "Okay, can you find me a WASHINGTON on my WASHINGTON that has a WASHINGTON?",
    "Okay, can you find me a WASHINGTON on my WASHINGTON that has a SOMETHING?",
    "Okay, can you find me a WASHINGTON on my WASHINGTON that has a SCHOOL?",
    "Okay, can you find me a WASHINGTON on my SOMETHING that has a WASHINGTON?",
    "Okay, can you find me a WASHINGTON on my SOMETHING that has a SOMETHING?",
    "Okay, can you find me a WASHINGTON on my SOMETHING that has a SCHOOL?",
    "Okay, can you find me a WASHINGTON on my SCHOOL that has a WASHINGTON?",
    "Okay, can you find me a WASHINGTON on my SCHOOL that has a SOMETHING?",
    "Okay, can you find me a WASHINGTON on my SCHOOL that has a SCHOOL?",

    "Okay, can you find me a SOMETHING on my WASHINGTON that has a WASHINGTON?",
    "Okay, can you find me a SOMETHING on my WASHINGTON that has a SOMETHING?",
    "Okay, can you find me a SOMETHING on my WASHINGTON that has a SCHOOL?",
    "Okay, can you find me a SOMETHING on my SOMETHING that has a WASHINGTON?",
    "Okay, can you find me a SOMETHING on my SOMETHING that has a SOMETHING?",
    "Okay, can you find me a SOMETHING on my SOMETHING that has a SCHOOL?",
    "Okay, can you find me a SOMETHING on my SCHOOL that has a WASHINGTON?",
    "Okay, can you find me a SOMETHING on my SCHOOL that has a SOMETHING?",
    "Okay, can you find me a SOMETHING on my SCHOOL that has a SCHOOL?",

    "Okay, can you find me a SCHOOL on my WASHINGTON that has a WASHINGTON?",
    "Okay, can you find me a SCHOOL on my WASHINGTON that has a SOMETHING?",
    "Okay, can you find me a SCHOOL on my WASHINGTON that has a SCHOOL?",
    "Okay, can you find me a SCHOOL on my SOMETHING that has a WASHINGTON?",
    "Okay, can you find me a SCHOOL on my SOMETHING that has a SOMETHING?",
    "Okay, can you find me a SCHOOL on my SOMETHING that has a SCHOOL?",
    "Okay, can you find me a SCHOOL on my SCHOOL that has a WASHINGTON?",
    "Okay, can you find me a SCHOOL on my SCHOOL that has a SOMETHING?",
    "Okay, can you find me a SCHOOL on my SCHOOL that has a SCHOOL?",

    "Find WASHINGTON near destination that accepts WASHINGTON and has a WASHINGTON.",
    "Find WASHINGTON near destination that accepts WASHINGTON and has a SOMETHING.",
    "Find WASHINGTON near destination that accepts WASHINGTON and has a SCHOOL.",
    "Find WASHINGTON near destination that accepts SOMETHING and has a WASHINGTON.",
    "Find WASHINGTON near destination that accepts SOMETHING and has a SOMETHING.",
    "Find WASHINGTON near destination that accepts SOMETHING and has a SCHOOL.",
    "Find WASHINGTON near destination that accepts SCHOOL and has a WASHINGTON.",
    "Find WASHINGTON near destination that accepts SCHOOL and has a SOMETHING.",
    "Find WASHINGTON near destination that accepts SCHOOL and has a SCHOOL.",

    "Find SOMETHING near destination that accepts WASHINGTON and has a WASHINGTON.",
    "Find SOMETHING near destination that accepts WASHINGTON and has a SOMETHING.",
    "Find SOMETHING near destination that accepts WASHINGTON and has a SCHOOL.",
    "Find SOMETHING near destination that accepts SOMETHING and has a WASHINGTON.",
    "Find SOMETHING near destination that accepts SOMETHING and has a SOMETHING.",
    "Find SOMETHING near destination that accepts SOMETHING and has a SCHOOL.",
    "Find SOMETHING near destination that accepts SCHOOL and has a WASHINGTON.",
    "Find SOMETHING near destination that accepts SCHOOL and has a SOMETHING.",
    "Find SOMETHING near destination that accepts SCHOOL and has a SCHOOL.",

    "Find SCHOOL near destination that accepts WASHINGTON and has a WASHINGTON.",
    "Find SCHOOL near destination that accepts WASHINGTON and has a SOMETHING.",
    "Find SCHOOL near destination that accepts WASHINGTON and has a SCHOOL.",
    "Find SCHOOL near destination that accepts SOMETHING and has a WASHINGTON.",
    "Find SCHOOL near destination that accepts SOMETHING and has a SOMETHING.",
    "Find SCHOOL near destination that accepts SOMETHING and has a SCHOOL.",
    "Find SCHOOL near destination that accepts SCHOOL and has a WASHINGTON.",
    "Find SCHOOL near destination that accepts SCHOOL and has a SOMETHING.",
    "Find SCHOOL near destination that accepts SCHOOL and has a SCHOOL.",

    "Find MONALISA near destination that accepts WASHINGTON and has a WASHINGTON.",
    "Find MONALISA near destination that accepts WASHINGTON and has a SOMETHING.",
    "Find MONALISA near destination that accepts WASHINGTON and has a SCHOOL.",
    "Find MONALISA near destination that accepts SOMETHING and has a WASHINGTON.",
    "Find MONALISA near destination that accepts SOMETHING and has a SOMETHING.",
    "Find MONALISA near destination that accepts SOMETHING and has a SCHOOL.",
    "Find MONALISA near destination that accepts SCHOOL and has a WASHINGTON.",
    "Find MONALISA near destination that accepts SCHOOL and has a SOMETHING.",
    "Find MONALISA near destination that accepts SCHOOL and has a SCHOOL.",

    "Find NOTEBOOK near destination that accepts WASHINGTON and has a WASHINGTON.",
    "Find NOTEBOOK near destination that accepts WASHINGTON and has a SOMETHING.",
    "Find NOTEBOOK near destination that accepts WASHINGTON and has a SCHOOL.",
    "Find NOTEBOOK near destination that accepts SOMETHING and has a WASHINGTON.",
    "Find NOTEBOOK near destination that accepts SOMETHING and has a SOMETHING.",
    "Find NOTEBOOK near destination that accepts SOMETHING and has a SCHOOL.",
    "Find NOTEBOOK near destination that accepts SCHOOL and has a WASHINGTON.",
    "Find NOTEBOOK near destination that accepts SCHOOL and has a SOMETHING.",
    "Find NOTEBOOK near destination that accepts SCHOOL and has a SCHOOL."
]
three_script = [
    "[SEARCH FROM:WASHINGTON  WHERE:[SEARCH GEOCODE WHERE:WASHINGTON and WASHINGTON]]",
    "[SEARCH FROM:WASHINGTON  WHERE:[SEARCH GEOCODE WHERE:WASHINGTON and SOMETHING]]",
    "[SEARCH FROM:WASHINGTON  WHERE:[SEARCH GEOCODE WHERE:WASHINGTON and SCHOOL]]",
    "[SEARCH FROM:WASHINGTON  WHERE:[SEARCH GEOCODE WHERE:SOMETHING and WASHINGTON]]",
    "[SEARCH FROM:WASHINGTON  WHERE:[SEARCH GEOCODE WHERE:SOMETHING and SCHOOL]]",
    "[SEARCH FROM:WASHINGTON  WHERE:[SEARCH GEOCODE WHERE:SOMETHING and SOMETHING]]",
    "[SEARCH FROM:WASHINGTON  WHERE:[SEARCH GEOCODE WHERE:SCHOOL and WASHINGTON]]",
    "[SEARCH FROM:WASHINGTON  WHERE:[SEARCH GEOCODE WHERE:SCHOOL and SOMETHING]]",
    "[SEARCH FROM:WASHINGTON  WHERE:[SEARCH GEOCODE WHERE:SCHOOL and SCHOOL]]",

    "[SEARCH FROM:SOMETHING  WHERE:[SEARCH GEOCODE WHERE:WASHINGTON and WASHINGTON]]",
    "[SEARCH FROM:SOMETHING  WHERE:[SEARCH GEOCODE WHERE:WASHINGTON and SOMETHING]]",
    "[SEARCH FROM:SOMETHING  WHERE:[SEARCH GEOCODE WHERE:WASHINGTON and SCHOOL]]",
    "[SEARCH FROM:SOMETHING  WHERE:[SEARCH GEOCODE WHERE:SOMETHING and WASHINGTON]]",
    "[SEARCH FROM:SOMETHING  WHERE:[SEARCH GEOCODE WHERE:SOMETHING and SCHOOL]]",
    "[SEARCH FROM:SOMETHING  WHERE:[SEARCH GEOCODE WHERE:SOMETHING and SOMETHING]]",
    "[SEARCH FROM:SOMETHING  WHERE:[SEARCH GEOCODE WHERE:SCHOOL and WASHINGTON]]",
    "[SEARCH FROM:SOMETHING  WHERE:[SEARCH GEOCODE WHERE:SCHOOL and SOMETHING]]",
    "[SEARCH FROM:SOMETHING  WHERE:[SEARCH GEOCODE WHERE:SCHOOL and SCHOOL]]",

    "[SEARCH FROM:SCHOOL  WHERE:[SEARCH GEOCODE WHERE:WASHINGTON and WASHINGTON]]",
    "[SEARCH FROM:SCHOOL  WHERE:[SEARCH GEOCODE WHERE:WASHINGTON and SOMETHING]]",
    "[SEARCH FROM:SCHOOL  WHERE:[SEARCH GEOCODE WHERE:WASHINGTON and SCHOOL]]",
    "[SEARCH FROM:SCHOOL  WHERE:[SEARCH GEOCODE WHERE:SOMETHING and WASHINGTON]]",
    "[SEARCH FROM:SCHOOL  WHERE:[SEARCH GEOCODE WHERE:SOMETHING and SCHOOL]]",
    "[SEARCH FROM:SCHOOL  WHERE:[SEARCH GEOCODE WHERE:SOMETHING and SOMETHING]]",
    "[SEARCH FROM:SCHOOL  WHERE:[SEARCH GEOCODE WHERE:SCHOOL and WASHINGTON]]",
    "[SEARCH FROM:SCHOOL  WHERE:[SEARCH GEOCODE WHERE:SCHOOL and SOMETHING]]",
    "[SEARCH FROM:SCHOOL  WHERE:[SEARCH GEOCODE WHERE:SCHOOL and SCHOOL]]",

    "[SEARCH ONE FROM:WASHINGTON WHERE:WASHINGTON WITH:WASHINGTON]",
    "[SEARCH ONE FROM:WASHINGTON WHERE:WASHINGTON WITH:SOMETHING]",
    "[SEARCH ONE FROM:WASHINGTON WHERE:WASHINGTON WITH:SCHOOL]",
    "[SEARCH ONE FROM:WASHINGTON WHERE:SOMETHING WITH:WASHINGTON]",
    "[SEARCH ONE FROM:WASHINGTON WHERE:SOMETHING WITH:SOMETHING]",
    "[SEARCH ONE FROM:WASHINGTON WHERE:SOMETHING WITH:SCHOOL]",
    "[SEARCH ONE FROM:WASHINGTON WHERE:SCHOOL WITH:WASHINGTON]",
    "[SEARCH ONE FROM:WASHINGTON WHERE:SCHOOL WITH:SOMETHING]",
    "[SEARCH ONE FROM:WASHINGTON WHERE:SCHOOL WITH:SCHOOL]",

    "[SEARCH ONE FROM:SOMETHING WHERE:WASHINGTON WITH:WASHINGTON]",
    "[SEARCH ONE FROM:SOMETHING WHERE:WASHINGTON WITH:SOMETHING]",
    "[SEARCH ONE FROM:SOMETHING WHERE:WASHINGTON WITH:SCHOOL]",
    "[SEARCH ONE FROM:SOMETHING WHERE:SOMETHING WITH:WASHINGTON]",
    "[SEARCH ONE FROM:SOMETHING WHERE:SOMETHING WITH:SOMETHING]",
    "[SEARCH ONE FROM:SOMETHING WHERE:SOMETHING WITH:SCHOOL]",
    "[SEARCH ONE FROM:SOMETHING WHERE:SCHOOL WITH:WASHINGTON]",
    "[SEARCH ONE FROM:SOMETHING WHERE:SCHOOL WITH:SOMETHING]",
    "[SEARCH ONE FROM:SOMETHING WHERE:SCHOOL WITH:SCHOOL]",

    "[SEARCH ONE FROM:SCHOOL WHERE:WASHINGTON WITH:WASHINGTON]",
    "[SEARCH ONE FROM:SCHOOL WHERE:WASHINGTON WITH:SOMETHING]",
    "[SEARCH ONE FROM:SCHOOL WHERE:WASHINGTON WITH:SCHOOL]",
    "[SEARCH ONE FROM:SCHOOL WHERE:SOMETHING WITH:WASHINGTON]",
    "[SEARCH ONE FROM:SCHOOL WHERE:SOMETHING WITH:SOMETHING]",
    "[SEARCH ONE FROM:SCHOOL WHERE:SOMETHING WITH:SCHOOL]",
    "[SEARCH ONE FROM:SCHOOL WHERE:SCHOOL WITH:WASHINGTON]",
    "[SEARCH ONE FROM:SCHOOL WHERE:SCHOOL WITH:SOMETHING]",
    "[SEARCH ONE FROM:SCHOOL WHERE:SCHOOL WITH:SCHOOL]",

    "[SEARCH ONE FROM:WASHINGTON WITH:WASHINGTON WITH:WASHINGTON]",
    "[SEARCH ONE FROM:WASHINGTON WITH:WASHINGTON WITH:SOMETHING]",
    "[SEARCH ONE FROM:WASHINGTON WITH:WASHINGTON WITH:SCHOOL]",
    "[SEARCH ONE FROM:WASHINGTON WITH:SOMETHING WITH:WASHINGTON]",
    "[SEARCH ONE FROM:WASHINGTON WITH:SOMETHING WITH:SOMETHING]",
    "[SEARCH ONE FROM:WASHINGTON WITH:SOMETHING WITH:SCHOOL]",
    "[SEARCH ONE FROM:WASHINGTON WITH:SCHOOL WITH:WASHINGTON]",
    "[SEARCH ONE FROM:WASHINGTON WITH:SCHOOL WITH:SOMETHING]",
    "[SEARCH ONE FROM:WASHINGTON WITH:SCHOOL WITH:SCHOOL]",

    "[SEARCH ONE FROM:SOMETHING WITH:WASHINGTON WITH:WASHINGTON]",
    "[SEARCH ONE FROM:SOMETHING WITH:WASHINGTON WITH:SOMETHING]",
    "[SEARCH ONE FROM:SOMETHING WITH:WASHINGTON WITH:SCHOOL]",
    "[SEARCH ONE FROM:SOMETHING WITH:SOMETHING WITH:WASHINGTON]",
    "[SEARCH ONE FROM:SOMETHING WITH:SOMETHING WITH:SOMETHING]",
    "[SEARCH ONE FROM:SOMETHING WITH:SOMETHING WITH:SCHOOL]",
    "[SEARCH ONE FROM:SOMETHING WITH:SCHOOL WITH:WASHINGTON]",
    "[SEARCH ONE FROM:SOMETHING WITH:SCHOOL WITH:SOMETHING]",
    "[SEARCH ONE FROM:SOMETHING WITH:SCHOOL WITH:SCHOOL]",

    "[SEARCH ONE FROM:SCHOOL WITH:WASHINGTON WITH:WASHINGTON]",
    "[SEARCH ONE FROM:SCHOOL WITH:WASHINGTON WITH:SOMETHING]",
    "[SEARCH ONE FROM:SCHOOL WITH:WASHINGTON WITH:SCHOOL]",
    "[SEARCH ONE FROM:SCHOOL WITH:SOMETHING WITH:WASHINGTON]",
    "[SEARCH ONE FROM:SCHOOL WITH:SOMETHING WITH:SOMETHING]",
    "[SEARCH ONE FROM:SCHOOL WITH:SOMETHING WITH:SCHOOL]",
    "[SEARCH ONE FROM:SCHOOL WITH:SCHOOL WITH:WASHINGTON]",
    "[SEARCH ONE FROM:SCHOOL WITH:SCHOOL WITH:SOMETHING]",
    "[SEARCH ONE FROM:SCHOOL WITH:SCHOOL WITH:SCHOOL]",

    "[SEARCH ONE FROM:MONALISA WITH:WASHINGTON WITH:WASHINGTON]",
    "[SEARCH ONE FROM:MONALISA WITH:WASHINGTON WITH:SOMETHING]",
    "[SEARCH ONE FROM:MONALISA WITH:WASHINGTON WITH:SCHOOL]",
    "[SEARCH ONE FROM:MONALISA WITH:SOMETHING WITH:WASHINGTON]",
    "[SEARCH ONE FROM:MONALISA WITH:SOMETHING WITH:SOMETHING]",
    "[SEARCH ONE FROM:MONALISA WITH:SOMETHING WITH:SCHOOL]",
    "[SEARCH ONE FROM:MONALISA WITH:SCHOOL WITH:WASHINGTON]",
    "[SEARCH ONE FROM:MONALISA WITH:SCHOOL WITH:SOMETHING]",
    "[SEARCH ONE FROM:MONALISA WITH:SCHOOL WITH:SCHOOL]",

    "[SEARCH ONE FROM:NOTEBOOK WITH:WASHINGTON WITH:WASHINGTON]",
    "[SEARCH ONE FROM:NOTEBOOK WITH:WASHINGTON WITH:SOMETHING]",
    "[SEARCH ONE FROM:NOTEBOOK WITH:WASHINGTON WITH:SCHOOL]",
    "[SEARCH ONE FROM:NOTEBOOK WITH:SOMETHING WITH:WASHINGTON]",
    "[SEARCH ONE FROM:NOTEBOOK WITH:SOMETHING WITH:SOMETHING]",
    "[SEARCH ONE FROM:NOTEBOOK WITH:SOMETHING WITH:SCHOOL]",
    "[SEARCH ONE FROM:NOTEBOOK WITH:SCHOOL WITH:WASHINGTON]",
    "[SEARCH ONE FROM:NOTEBOOK WITH:SCHOOL WITH:SOMETHING]",
    "[SEARCH ONE FROM:NOTEBOOK WITH:SCHOOL WITH:SCHOOL]"
]
message_total = [one,two,three]
message_embeddings_total=[]

script_total = [one_script, two_script, three_script]

google_entity_type ={0:'UNKNOWN', 1:'PERSON', 2:'LOCATION', 3:'ORGANIZATION', 4:'EVENT', 5:'WORK_OF_ART', 6:'CONSUMER_GOOD', 7:'OTHER'}
entity_type ={0:'X', 1:'DAVID', 2:'WASHINGTON', 3:'SCHOOL', 4:'MEETTING', 5:'MONALISA', 6:'NOTEBOOK', 7:'SOMETHING'}
i_entity_type ={'X':0, 'DAVID':1, 'WASHINGTON':2, 'SCHOOL':3, 'MEETTING':4, 'MONALISA':5, 'NOTEBOOK':6, 'SOMETHING':7}
Times = ['today','tomorrow','afternoon','morning','evening','yesterday', 'now', ]
line_time=''
for i in range(len(Times)):
    if Times[i] in lines:
        line_time=Times[i]
        lines = lines.replace(Times[i], 'Time')

client = language.LanguageServiceClient()
document = types.Document(
        content=lines,
        language='en',
        type=enums.Document.Type.PLAIN_TEXT)

entities = client.analyze_entities(document).entities

result = lines

for entity in entities:
    result = result.replace(entity.name, entity_type[entity.type])

print("\n\ninput : {}".format(lines))
print("Replace nouns: {}\n\n".format(result))


module_url = "https://tfhub.dev/google/universal-sentence-encoder/1" #@param ["https://tfhub.dev/google/universal-sentence-encoder/1", "https://tfhub.dev/google/universal-sentence-encoder-large/1"]

# Import the Universal Sentence Encoder's TF Hub module
embed = hub.Module(module_url)

# Reduce logging output.
tf.logging.set_verbosity(tf.logging.ERROR)


# if not os.path.exists("./profile2.bin"):
#     print("There is no profile2.bin. Making profile2.bin")
#     with tf.Session() as session:
#         session.run([tf.global_variables_initializer(), tf.tables_initializer()])
#         message_embeddings = session.run(embed(messages2))
#         with open('profile2.bin', 'wb') as f:
#             pickle.dump(message_embeddings, f)
#     print("Finish make profile!")
# else:
#     print("profile2.bin exists")
#     with open('./profile2.bin', 'rb') as f:
#         message_embeddings = pickle.load(f)

# with tf.Session() as session:
#     session.run([tf.global_variables_initializer(), tf.tables_initializer()])
#     for message in message_total:
#         message_embeddings = session.run(embed(message))
#         message_embeddings_total = message_embeddings_total.append([message_embeddings])
# for message in message_total:
#     message_embeddings = session.run(embed(message_total[0]))
#     message_embeddings_total = message_embeddings_total.append([message_embeddings])
# test = session.run(embed(message_total[0]))
#


# with tf.Session() as session:
#     session.run([tf.global_variables_initializer(), tf.tables_initializer()])
#     for message in message_total:
#         message_embeddings = session.run(embed(message))
#         message_embeddings_total.append(message_embeddings)
#     with open('profile2.bin', 'wb') as f:
#         pickle.dump(message_embeddings_total, f)
# print("Finish make profile!")

# with tf.Session() as session:
#     session.run([tf.global_variables_initializer(), tf.tables_initializer()])
#     for message in message_total:
#         message_embeddings = session.run(embed(message))
#         message_embeddings_total.append(message_embeddings)

if not os.path.exists("./profile2.bin"):
    print("There is no profile2.bin. Making profile2.bin")
    with tf.Session() as session:
        session.run([tf.global_variables_initializer(), tf.tables_initializer()])
        for message in message_total:
            message_embeddings = session.run(embed(message))
            message_embeddings_total.append(message_embeddings)
        with open('profile2.bin', 'wb') as f:
            pickle.dump(message_embeddings_total, f)
    print("Finish make profile!")
else:
    print("profile2.bin exists")
    with open('./profile2.bin', 'rb') as f:
        message_embeddings_total = pickle.load(f)

print("\n\ncompare with : "+ str(len(message_total[0]))+", "+str(len(message_total[1]))+", "+str(len(message_total[2])))
print("compare with : "+ str(len(message_embeddings_total[0]))+", "+str(len(message_embeddings_total[1]))+", "+str(len(message_embeddings_total[2])))

with tf.Session() as session:
  session.run([tf.global_variables_initializer(), tf.tables_initializer()])
  test_message_embeddings = session.run(embed([result]))

test_labels = [1]
minimum = 100
minimum_index = 0
entity_num = len(entities)
# for i, message_embedding in enumerate(message_embeddings):
#     error = rmse(np.array(message_embedding), np.array(test_message_embeddings))
#     if minimum > error:
#       minimum = error
#       minimum_index = i

for i, message_embedding in enumerate(message_embeddings_total[entity_num-1]):
    error = rmse(np.array(message_embedding), np.array(test_message_embeddings))
    if minimum > error:
      minimum = error
      minimum_index = i


print("\n\n\n\n\n")


print("Minimum RMSE value: {}".format(minimum))
print("Most similar script: {}".format(script_total[entity_num-1][minimum_index]))
print("Estimation: {}".format(minimum_index))
#print("Answer: {}\n".format(test_label))
result2 = script_total[entity_num-1][minimum_index] #query

Dict_entitis={}
K=[] #Keys = Type
V=[] #Values = Names
google=[]
for entity in entities:
    # Dict_entitis[entity.name]=entity_type[entity.type]
    google.append(google_entity_type[entity.type])
    K.append(entity_type[entity.type])
    V.append(entity.name)


# print("Dict_entitis : ", Dict_entitis)
print("Entities : ", google)
print("Keys : ", K)
print("Values : ", V)
print("entity_number : ", entity_num)

# for key, value in Dict_entitis.items():
#     result2 = result2.replace(value, key)

number = len(K)
for i in range(0, number):
    result2 = result2.replace(K[i], V[i],1)

if line_time is not '':
    result2 = result2.replace('Time', line_time,1)

print("input: {}".format(lines))
print("Replace nouns: {}".format(result))
print("Selected Sentence: {}".format(message_total[entity_num-1][minimum_index]))
print("Query: {}".format(result2))
